# SPDX-FileCopyrightText: Copyright (c) 2014-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: simian
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  simian:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
      - run: wget --quiet http://public.yegor256.com/simian.jar -O /tmp/simian.jar
      - run: java -jar /tmp/simian.jar -threshold=45 "-excludes=**/EOsocketTest.java" "-excludes=**/gen" "-excludes=**/it" "**/*.java"
