# SPDX-FileCopyrightText: Copyright (c) 2014-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: xcop
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  xcop:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: g4s8/xcop-action@master
